/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contract {
  'id' : bigint,
  'title' : string,
  'endDate' : Time,
  'value' : number,
  'contractType' : ContractType,
  'contractStatus' : ContractStatus,
  'startDate' : Time,
}
export type ContractStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export type ContractType = { 'in' : { 'client' : string } } |
  { 'out' : { 'vendor' : string } };
export type Department = { 'hr' : null } |
  { 'finance' : null } |
  { 'marketing' : null } |
  { 'sales' : null } |
  { 'engineering' : null } |
  { 'operations' : null };
export interface Employee {
  'id' : bigint,
  'active' : boolean,
  'name' : string,
  'department' : Department,
}
export interface ExpenseEntry {
  'date' : Time,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export interface IncomeEntry {
  'date' : Time,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export interface Record {
  'id' : bigint,
  'title' : string,
  'contractType' : ContractType,
  'details' : Contract,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'employeeId' : [] | [bigint] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContract' : ActorMethod<
    [string, ContractType, number, Time, Time, ContractStatus],
    bigint
  >,
  'addEmployee' : ActorMethod<[string, Department], bigint>,
  'addExpense' : ActorMethod<[Time, string, string, number], bigint>,
  'addIncome' : ActorMethod<[Time, string, string, number], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContract' : ActorMethod<[bigint], Contract>,
  'getContractByTitle' : ActorMethod<[string], Array<Record>>,
  'getEmployee' : ActorMethod<[bigint], Employee>,
  'getExpense' : ActorMethod<[bigint], ExpenseEntry>,
  'getIncome' : ActorMethod<[bigint], IncomeEntry>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkEmployeeToPrincipal' : ActorMethod<[bigint, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchContractByTitle' : ActorMethod<[string], Array<Record>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];