/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContractType = IDL.Variant({
  'in' : IDL.Record({ 'client' : IDL.Text }),
  'out' : IDL.Record({ 'vendor' : IDL.Text }),
});
export const Time = IDL.Int;
export const ContractStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Department = IDL.Variant({
  'hr' : IDL.Null,
  'finance' : IDL.Null,
  'marketing' : IDL.Null,
  'sales' : IDL.Null,
  'engineering' : IDL.Null,
  'operations' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'employeeId' : IDL.Opt(IDL.Nat),
});
export const Contract = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'endDate' : Time,
  'value' : IDL.Float64,
  'contractType' : ContractType,
  'contractStatus' : ContractStatus,
  'startDate' : Time,
});
export const Record = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'contractType' : ContractType,
  'details' : Contract,
});
export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'department' : Department,
});
export const ExpenseEntry = IDL.Record({
  'date' : Time,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const IncomeEntry = IDL.Record({
  'date' : Time,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContract' : IDL.Func(
      [IDL.Text, ContractType, IDL.Float64, Time, Time, ContractStatus],
      [IDL.Nat],
      [],
    ),
  'addEmployee' : IDL.Func([IDL.Text, Department], [IDL.Nat], []),
  'addExpense' : IDL.Func(
      [Time, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'addIncome' : IDL.Func(
      [Time, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContract' : IDL.Func([IDL.Nat], [Contract], ['query']),
  'getContractByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Record)], ['query']),
  'getEmployee' : IDL.Func([IDL.Nat], [Employee], ['query']),
  'getExpense' : IDL.Func([IDL.Nat], [ExpenseEntry], ['query']),
  'getIncome' : IDL.Func([IDL.Nat], [IncomeEntry], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkEmployeeToPrincipal' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchContractByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Record)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContractType = IDL.Variant({
    'in' : IDL.Record({ 'client' : IDL.Text }),
    'out' : IDL.Record({ 'vendor' : IDL.Text }),
  });
  const Time = IDL.Int;
  const ContractStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Department = IDL.Variant({
    'hr' : IDL.Null,
    'finance' : IDL.Null,
    'marketing' : IDL.Null,
    'sales' : IDL.Null,
    'engineering' : IDL.Null,
    'operations' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'employeeId' : IDL.Opt(IDL.Nat),
  });
  const Contract = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'endDate' : Time,
    'value' : IDL.Float64,
    'contractType' : ContractType,
    'contractStatus' : ContractStatus,
    'startDate' : Time,
  });
  const Record = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'contractType' : ContractType,
    'details' : Contract,
  });
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'department' : Department,
  });
  const ExpenseEntry = IDL.Record({
    'date' : Time,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const IncomeEntry = IDL.Record({
    'date' : Time,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContract' : IDL.Func(
        [IDL.Text, ContractType, IDL.Float64, Time, Time, ContractStatus],
        [IDL.Nat],
        [],
      ),
    'addEmployee' : IDL.Func([IDL.Text, Department], [IDL.Nat], []),
    'addExpense' : IDL.Func(
        [Time, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'addIncome' : IDL.Func(
        [Time, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContract' : IDL.Func([IDL.Nat], [Contract], ['query']),
    'getContractByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Record)], ['query']),
    'getEmployee' : IDL.Func([IDL.Nat], [Employee], ['query']),
    'getExpense' : IDL.Func([IDL.Nat], [ExpenseEntry], ['query']),
    'getIncome' : IDL.Func([IDL.Nat], [IncomeEntry], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkEmployeeToPrincipal' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchContractByTitle' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Record)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };