/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type ContractType = {
    __kind__: "in";
    in: {
        client: string;
    };
} | {
    __kind__: "out";
    out: {
        vendor: string;
    };
};
export interface Record_ {
    id: bigint;
    title: string;
    contractType: ContractType;
    details: Contract;
}
export interface Employee {
    id: bigint;
    active: boolean;
    name: string;
    department: Department;
}
export interface ExpenseEntry {
    date: Time;
    description: string;
    category: string;
    amount: number;
}
export interface IncomeEntry {
    date: Time;
    description: string;
    category: string;
    amount: number;
}
export interface UserProfile {
    name: string;
    employeeId?: bigint;
}
export interface Contract {
    id: bigint;
    title: string;
    endDate: Time;
    value: number;
    contractType: ContractType;
    contractStatus: ContractStatus;
    startDate: Time;
}
export enum ContractStatus {
    active = "active",
    cancelled = "cancelled",
    completed = "completed"
}
export enum Department {
    hr = "hr",
    finance = "finance",
    marketing = "marketing",
    sales = "sales",
    engineering = "engineering",
    operations = "operations"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addContract(title: string, contractType: ContractType, value: number, startDate: Time, endDate: Time, status: ContractStatus): Promise<bigint>;
    addEmployee(name: string, department: Department): Promise<bigint>;
    addExpense(date: Time, category: string, description: string, amount: number): Promise<bigint>;
    addIncome(date: Time, category: string, description: string, amount: number): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContract(id: bigint): Promise<Contract>;
    getContractByTitle(title: string): Promise<Array<Record_>>;
    getEmployee(id: bigint): Promise<Employee>;
    getExpense(id: bigint): Promise<ExpenseEntry>;
    getIncome(id: bigint): Promise<IncomeEntry>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    linkEmployeeToPrincipal(employeeId: bigint, principal: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchContractByTitle(title: string): Promise<Array<Record_>>;
}
import type { Contract as _Contract, ContractStatus as _ContractStatus, ContractType as _ContractType, Department as _Department, Employee as _Employee, Record as _Record, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addContract(arg0: string, arg1: ContractType, arg2: number, arg3: Time, arg4: Time, arg5: ContractStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addContract(arg0, to_candid_ContractType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_ContractStatus_n3(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContract(arg0, to_candid_ContractType_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_ContractStatus_n3(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addEmployee(arg0: string, arg1: Department): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(arg0, to_candid_Department_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(arg0, to_candid_Department_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addExpense(arg0: Time, arg1: string, arg2: string, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addIncome(arg0: Time, arg1: string, arg2: string, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addIncome(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIncome(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContract(arg0: bigint): Promise<Contract> {
        if (this.processError) {
            try {
                const result = await this.actor.getContract(arg0);
                return from_candid_Contract_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContract(arg0);
            return from_candid_Contract_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContractByTitle(arg0: string): Promise<Array<Record_>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContractByTitle(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContractByTitle(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployee(arg0: bigint): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_Employee_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_Employee_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpense(arg0: bigint): Promise<ExpenseEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return result;
        }
    }
    async getIncome(arg0: bigint): Promise<IncomeEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncome(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncome(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async linkEmployeeToPrincipal(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkEmployeeToPrincipal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkEmployeeToPrincipal(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchContractByTitle(arg0: string): Promise<Array<Record_>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchContractByTitle(arg0);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchContractByTitle(arg0);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ContractStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContractStatus): ContractStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ContractType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContractType): ContractType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Contract_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Contract): Contract {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Department_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Department): Department {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Employee_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Record): Record_ {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    employeeId: [] | [bigint];
}): {
    name: string;
    employeeId?: bigint;
} {
    return {
        name: value.name,
        employeeId: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.employeeId))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    endDate: _Time;
    value: number;
    contractType: _ContractType;
    contractStatus: _ContractStatus;
    startDate: _Time;
}): {
    id: bigint;
    title: string;
    endDate: Time;
    value: number;
    contractType: ContractType;
    contractStatus: ContractStatus;
    startDate: Time;
} {
    return {
        id: value.id,
        title: value.title,
        endDate: value.endDate,
        value: value.value,
        contractType: from_candid_ContractType_n17(_uploadFile, _downloadFile, value.contractType),
        contractStatus: from_candid_ContractStatus_n19(_uploadFile, _downloadFile, value.contractStatus),
        startDate: value.startDate
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    contractType: _ContractType;
    details: _Contract;
}): {
    id: bigint;
    title: string;
    contractType: ContractType;
    details: Contract;
} {
    return {
        id: value.id,
        title: value.title,
        contractType: from_candid_ContractType_n17(_uploadFile, _downloadFile, value.contractType),
        details: from_candid_Contract_n15(_uploadFile, _downloadFile, value.details)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    active: boolean;
    name: string;
    department: _Department;
}): {
    id: bigint;
    active: boolean;
    name: string;
    department: Department;
} {
    return {
        id: value.id,
        active: value.active,
        name: value.name,
        department: from_candid_Department_n26(_uploadFile, _downloadFile, value.department)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    in: {
        client: string;
    };
} | {
    out: {
        vendor: string;
    };
}): {
    __kind__: "in";
    in: {
        client: string;
    };
} | {
    __kind__: "out";
    out: {
        vendor: string;
    };
} {
    return "in" in value ? {
        __kind__: "in",
        in: value.in
    } : "out" in value ? {
        __kind__: "out",
        out: value.out
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): ContractStatus {
    return "active" in value ? ContractStatus.active : "cancelled" in value ? ContractStatus.cancelled : "completed" in value ? ContractStatus.completed : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hr: null;
} | {
    finance: null;
} | {
    marketing: null;
} | {
    sales: null;
} | {
    engineering: null;
} | {
    operations: null;
}): Department {
    return "hr" in value ? Department.hr : "finance" in value ? Department.finance : "marketing" in value ? Department.marketing : "sales" in value ? Department.sales : "engineering" in value ? Department.engineering : "operations" in value ? Department.operations : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Record>): Array<Record_> {
    return value.map((x)=>from_candid_Record_n22(_uploadFile, _downloadFile, x));
}
function to_candid_ContractStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContractStatus): _ContractStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ContractType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContractType): _ContractType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Department_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): _Department {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    employeeId?: bigint;
}): {
    name: string;
    employeeId: [] | [bigint];
} {
    return {
        name: value.name,
        employeeId: value.employeeId ? candid_some(value.employeeId) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "in";
    in: {
        client: string;
    };
} | {
    __kind__: "out";
    out: {
        vendor: string;
    };
}): {
    in: {
        client: string;
    };
} | {
    out: {
        vendor: string;
    };
} {
    return value.__kind__ === "in" ? {
        in: value.in
    } : value.__kind__ === "out" ? {
        out: value.out
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContractStatus): {
    active: null;
} | {
    cancelled: null;
} | {
    completed: null;
} {
    return value == ContractStatus.active ? {
        active: null
    } : value == ContractStatus.cancelled ? {
        cancelled: null
    } : value == ContractStatus.completed ? {
        completed: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Department): {
    hr: null;
} | {
    finance: null;
} | {
    marketing: null;
} | {
    sales: null;
} | {
    engineering: null;
} | {
    operations: null;
} {
    return value == Department.hr ? {
        hr: null
    } : value == Department.finance ? {
        finance: null
    } : value == Department.marketing ? {
        marketing: null
    } : value == Department.sales ? {
        sales: null
    } : value == Department.engineering ? {
        engineering: null
    } : value == Department.operations ? {
        operations: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
